services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"  # Add this line
    ports:
      - "80:80"
      - "443:443"  # Add this line
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - crys-sports-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/p1t0nn/crys-sports:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`crys-sports.com`)"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
    container_name: crys-sports
    ports:
      - "3000:3000"  # Add this line for debugging
    secrets:
      - database_url
      - supabase_url
      - supabase_anon_key
      - resend_api_key
      - jwt_secret
      - redis_url
      - redis_token
    restart: always
    networks:
      - crys-sports-network

networks:
  crys-sports-network:
    driver: bridge

secrets:
  database_url:
    file: /home/ognjen/secrets/database_url.txt
  supabase_url:
    file: /home/ognjen/secrets/supabase_url.txt
  supabase_anon_key:
    file: /home/ognjen/secrets/supabase_anon_key.txt
  resend_api_key:
    file: /home/ognjen/secrets/resend_api_key.txt
  jwt_secret:
    file: /home/ognjen/secrets/jwt_secret.txt
  redis_url:
    file: /home/ognjen/secrets/redis_url.txt
  redis_token:
    file: /home/ognjen/secrets/redis_token.txt